/**
 * Opportunities API Route - List opportunities with filters
 * Requirements: 5.2, 5.3, 5.5
 */

import { NextRequest, NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { requireAuth } from '@/lib/auth';
import { clientStore, opportunityStore } from '@/lib/data/stores';
import { accessControlService } from '@/lib/services/accessControlService';
import { ecosystemService } from '@/lib/services/ecosystemService';
import { opportunityDetectionService } from '@/lib/services/opportunityDetectionService';
import { initializeMockData } from '@/lib/data/initMockData';
import type { Opportunity } from '@/lib/models';

type ExternalOpportunityPayload = {
    id?: string;
    title: string;
    rm1Id: string;
    rm2Id: string;
    client1: {
        id: string;
        companyName: string;
        ecosystemPositions: string[];
        geography: string;
        revenue?: number;
        esgAlignment?: string;
        rmId: string;
    };
    client2: {
        id: string;
        companyName: string;
        ecosystemPositions: string[];
        geography: string;
        revenue?: number;
        esgAlignment?: string;
        rmId: string;
    };
    matchScore: number;
    confidence?: 'high' | 'medium' | 'low';
    reasoning?: string;
    pairing?: string;
    geographicProximity?: string;
};

async function fetchExternalFallbackOpportunities(): Promise<Opportunity[]> {
    const baseUrl = process.env.MATCHING_API_URL || 'http://127.0.0.1:8001';

    try {
        const response = await fetch(`${baseUrl}/opportunities?min_score=60&limit=120`, {
            cache: 'no-store'
        });

        if (!response.ok) {
            return [];
        }

        const data = await response.json() as {
            opportunities?: ExternalOpportunityPayload[];
        };

        const external = data.opportunities || [];
        const now = new Date();

        return external
            .filter((item) => item.rm1Id !== item.rm2Id)
            .map((item) => {
                const pos1 = item.client1.ecosystemPositions[0] as any;
                const pos2 = item.client2.ecosystemPositions[0] as any;
                const suggestedProducts = ecosystemService.getBankingProductsForPair(pos1, pos2);
                const normalizedScore = Math.max(0, Math.min(100, Number(item.matchScore || 0)));
                const confidence = item.confidence || (normalizedScore >= 80 ? 'high' : normalizedScore >= 65 ? 'medium' : 'low');

                return {
                    id: item.id || randomUUID(),
                    title: item.title || `${item.client1.companyName} × ${item.client2.companyName}`,
                    client1: {
                        id: item.client1.id,
                        companyName: item.client1.companyName,
                        ecosystemPositions: item.client1.ecosystemPositions as any,
                        geography: item.client1.geography,
                        revenue: Number(item.client1.revenue || 0),
                        esgAlignment: item.client1.esgAlignment || 'N/A',
                        rmId: item.client1.rmId,
                        createdAt: now,
                        updatedAt: now,
                    },
                    client2: {
                        id: item.client2.id,
                        companyName: item.client2.companyName,
                        ecosystemPositions: item.client2.ecosystemPositions as any,
                        geography: item.client2.geography,
                        revenue: Number(item.client2.revenue || 0),
                        esgAlignment: item.client2.esgAlignment || 'N/A',
                        rmId: item.client2.rmId,
                        createdAt: now,
                        updatedAt: now,
                    },
                    rm1Id: item.rm1Id,
                    rm2Id: item.rm2Id,
                    trigger: item.geographicProximity
                        ? `${item.pairing || 'Cross-ecosystem pairing'} with ${item.geographicProximity.toLowerCase()} proximity.`
                        : `${item.pairing || 'Cross-ecosystem pairing'} identified as a matching opportunity.`,
                    suggestedBankingProducts: suggestedProducts,
                    matchScore: normalizedScore,
                    reasoning: item.reasoning || 'Generated by Python matching service.',
                    confidence,
                    createdAt: now,
                    flaggedForReview: confidence === 'low',
                } as Opportunity;
            });
    } catch {
        return [];
    }
}

function buildFallbackOpportunity(candidate: {
    client1: Opportunity['client1'];
    client2: Opportunity['client2'];
    ecosystemPositionPair: [string, string];
}): Opportunity {
    const [pos1, pos2] = candidate.ecosystemPositionPair;
    const products = ecosystemService.getBankingProductsForPair(pos1 as any, pos2 as any);
    const complementary = ecosystemService.arePositionsComplementary(pos1 as any, pos2 as any);
    const sameGeography = candidate.client1.geography === candidate.client2.geography;
    const revenueRatio =
        Math.min(candidate.client1.revenue, candidate.client2.revenue) /
        Math.max(candidate.client1.revenue, candidate.client2.revenue);

    let score = 45;
    if (complementary) score += 20;
    if (products.length > 0) score += 15;
    if (sameGeography) score += 5;
    score += Math.round(revenueRatio * 15);
    score = Math.max(0, Math.min(100, score));

    const confidence: 'high' | 'medium' | 'low' = score >= 80 ? 'high' : score >= 65 ? 'medium' : 'low';
    const productNames = products.slice(0, 2).map((p) => p.name).join(', ');

    return {
        id: randomUUID(),
        title: `${candidate.client1.companyName} × ${candidate.client2.companyName}`,
        client1: candidate.client1,
        client2: candidate.client2,
        rm1Id: candidate.client1.rmId,
        rm2Id: candidate.client2.rmId,
        trigger: `${pos1} and ${pos2} create a cross-segment banking opportunity${sameGeography ? ' in the same region' : ''}.`,
        suggestedBankingProducts: products,
        matchScore: score,
        reasoning:
            products.length > 0
                ? `Position fit and value-chain complementarity indicate potential for ${productNames}.`
                : 'Cross-segment pairing with strategic relationship potential; manual product qualification recommended.',
        confidence,
        createdAt: new Date(),
        flaggedForReview: confidence === 'low'
    };
}

async function ensureFallbackOpportunities(): Promise<void> {
    const existingOpportunities = opportunityStore.getAll();
    if (existingOpportunities.length > 0) {
        const existingPairCount = new Set(
            existingOpportunities.map((opp) => [opp.rm1Id, opp.rm2Id].sort().join('|'))
        ).size;

        // Keep existing opportunities only if they already show good RM diversity.
        if (existingPairCount >= 3) {
            return;
        }

        // Re-seed low-diversity fallback data.
        opportunityStore.clear();
    }

    const clients = clientStore.getAll();
    if (clients.length < 2) {
        return;
    }

    const externalScored = await fetchExternalFallbackOpportunities();
    let scored = externalScored.sort((a, b) => b.matchScore - a.matchScore);

    if (scored.length === 0) {
        const candidates = opportunityDetectionService.generateCandidatePairs(clients);
        scored = candidates
            .map((candidate) => buildFallbackOpportunity(candidate as any))
            .filter((opp) => opp.matchScore >= 60)
            .sort((a, b) => b.matchScore - a.matchScore);
    }

    // Deduplicate by client pair (keep best-scoring variant of the pair).
    const uniqueByClientPair = new Map<string, Opportunity>();
    for (const opp of scored) {
        const clientPairKey = [opp.client1.id, opp.client2.id].sort().join('|');
        if (!uniqueByClientPair.has(clientPairKey)) {
            uniqueByClientPair.set(clientPairKey, opp);
        }
    }

    // Group by RM pair to ensure opportunities span multiple RM combinations.
    const groupedByRmPair = new Map<string, Opportunity[]>();
    for (const opp of uniqueByClientPair.values()) {
        const rmPairKey = [opp.rm1Id, opp.rm2Id].sort().join('|');
        if (!groupedByRmPair.has(rmPairKey)) {
            groupedByRmPair.set(rmPairKey, []);
        }
        groupedByRmPair.get(rmPairKey)!.push(opp);
    }

    // Sort each RM-pair bucket by score descending.
    for (const bucket of groupedByRmPair.values()) {
        bucket.sort((a, b) => b.matchScore - a.matchScore);
    }

    const rmPairKeys = Array.from(groupedByRmPair.keys()).sort((a, b) => {
        const aTop = groupedByRmPair.get(a)?.[0]?.matchScore ?? 0;
        const bTop = groupedByRmPair.get(b)?.[0]?.matchScore ?? 0;
        return bTop - aTop;
    });

    // Round-robin selection across RM pairs for diversity.
    const maxTotal = 30;
    const maxPerRmPair = 6;
    const selected: Opportunity[] = [];
    const selectedPerPair = new Map<string, number>();

    while (selected.length < maxTotal) {
        let pickedInRound = false;

        for (const rmPairKey of rmPairKeys) {
            if (selected.length >= maxTotal) {
                break;
            }

            const used = selectedPerPair.get(rmPairKey) ?? 0;
            if (used >= maxPerRmPair) {
                continue;
            }

            const bucket = groupedByRmPair.get(rmPairKey);
            if (!bucket || bucket.length === 0) {
                continue;
            }

            const next = bucket.shift();
            if (!next) {
                continue;
            }

            selected.push(next);
            selectedPerPair.set(rmPairKey, used + 1);
            pickedInRound = true;
        }

        if (!pickedInRound) {
            break;
        }
    }

    for (const opportunity of selected) {
        opportunityStore.create(opportunity);
    }
}

export async function GET(request: NextRequest) {
    try {
        // Authenticate the RM (Requirement 7.1)
        const rm = await requireAuth();

        await initializeMockData();
        await ensureFallbackOpportunities();

        // Get query parameters for filtering
        const searchParams = request.nextUrl.searchParams;
        const clientName = searchParams.get('clientName');
        const ecosystemPosition = searchParams.get('ecosystemPosition');
        const rmFilter = searchParams.get('rm');
        const limit = searchParams.get('limit') ? parseInt(searchParams.get('limit')!) : undefined;

        // Get opportunities for this RM (Requirement 5.2)
        let opportunities = opportunityStore.getByRMSorted(rm.id);

        // Apply filters (Requirement 5.3)
        if (clientName) {
            const lowerClientName = clientName.toLowerCase();
            opportunities = opportunities.filter(opp =>
                opp.client1.companyName.toLowerCase().includes(lowerClientName) ||
                opp.client2.companyName.toLowerCase().includes(lowerClientName)
            );
        }

        if (ecosystemPosition) {
            opportunities = opportunities.filter(opp =>
                opp.client1.ecosystemPositions.includes(ecosystemPosition as any) ||
                opp.client2.ecosystemPositions.includes(ecosystemPosition as any)
            );
        }

        if (rmFilter) {
            opportunities = opportunities.filter(opp =>
                opp.rm1Id === rmFilter || opp.rm2Id === rmFilter
            );
        }

        // Apply limit if specified
        if (limit && limit > 0) {
            opportunities = opportunities.slice(0, limit);
        }

        // Redact client data for cross-RM viewing
        const redactedOpportunities = opportunities.map(opp => {
            const redactedOpp: any = { ...opp };

            // Redact client1 if not owned by current RM
            if (opp.client1.rmId !== rm.id) {
                redactedOpp.client1 = accessControlService.redactClientForCrossRMView(opp.client1);
            }

            // Redact client2 if not owned by current RM
            if (opp.client2.rmId !== rm.id) {
                redactedOpp.client2 = accessControlService.redactClientForCrossRMView(opp.client2);
            }

            return redactedOpp;
        });

        // Log access
        await accessControlService.logAccess(
            rm.id,
            'opportunity',
            'list',
            'read',
            { filters: { clientName, ecosystemPosition, rmFilter }, count: redactedOpportunities.length }
        );

        return NextResponse.json({
            success: true,
            data: redactedOpportunities,
            count: redactedOpportunities.length
        });

    } catch (error) {
        if (error instanceof Error && error.message === 'Authentication required') {
            return NextResponse.json(
                { success: false, error: 'Authentication required' },
                { status: 401 }
            );
        }

        console.error('Error fetching opportunities:', error);
        return NextResponse.json(
            { success: false, error: 'Failed to fetch opportunities' },
            { status: 500 }
        );
    }
}
